### ISSUE TITLE
Fix crash on first startup (Geolocator.RequestAccessAsync)

### ISSUE THREAD

**Issue by mjeanrichard** [mjeanrichard/OutdoorTracker#29]
### Stacktrace

<pre>System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule;CoreApplication_UnhandledErrorDetected;;</pre>

### Reason

A method was called at an unexpected time. (Excep_FromHResult 0x8000000E)
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/352080/app_versions/23/crash_reasons/138234347](https://rink.hockeyapp.net/manage/apps/352080/app_versions/23/crash_reasons/138234347)

**Comment by RaminMT** [comment]
Hi,
I got same error, I call a method in `App.xaml.cs` that uses `Geolocator.RequestAccessAsync` but it result in same error. Maybe it's good to know that when the method starts, my MainPage is constructed successfully.
My project target version is 15063 & uses 14393 as min version, and I update `Microsoft.NETCore.UniversalWindowsPlatform` to v5.3.3
Any idea on why this error happens?

**Comment by mjeanrichard** [comment]
Hi @RaminMT,

I am sorry, but I have not even been able to reproduce this bug. If you find out why it happens, please tell me.

Thanks,
Meini

**Comment by RaminMT** [comment]
Hi @mjeanrichard 
It's simple, In `App.xaml.cs` ctor use `Windows.Devices.Geolocation.Geolocator.RequestAccessAsync().GetResults();`
Or create an `async void` method with `var x = await indows.Devices.Geolocation.Geolocator.RequestAccessAsync();` as body, And call it in `App.xaml.cs` ctor.

Thanks

**Comment by RaminMT** [comment]
@mjeanrichard Did you tried that?

**Comment by mjeanrichard** [comment]
No, I never tried that and I never will. I don't think you are supposed to call that in a Constructor. Especially not in the ``app.xaml.cs`` ctor. 
There is a reason why that method is async and its usually a bad idea to call async methods from a ctor. So your Problem is probably that you are calling it synchronously from a ctor, but that function expects to be able to show a UI and it probably can't because the app has not been completely constructed. 
Here, in my case, it seems to be randomly failing and I am not sure when (I assume that it is some kind of a timing issue). But most of the time it works fine.

Also you should make sure that this method is called on the UI-Thread (which you can't when using it from the ``app.xaml.cs`` ctor)!

**Comment by RaminMT** [comment]
I see what you mean, That was an example.
Actually in my project this is the structure:
An static method on another class calls the api.
In `App.xaml.cs` I have a sync method named "Initialize", which calls that method.
In `App.xaml.cs` ctor, I call "initialize" method.

I've tracked my code with breakpoints, I know when the app reaches to the api call, I've got a active view so why not it work?

**Comment by mjeanrichard** [comment]
It does not matter if you put it in another method. It must should be async and it must be called on the UI Thread. I assume that those two things are not true in your case. But this is not the rigt place to discuss your problem (which is probably different from mine, since this issue is actually gone, since I made sure that it was always called on the UI-Thread).

So Post a Stackoverflow Question and I will answer you there.

**Comment by RaminMT** [comment]
Thank you, I thought this is an issue on Microsoft 😃 so forgive me 😊
I’ll do post a Stackoverflow Question

Thanks

Sent from Mail for Windows 10
